chore: [CO-956] standalone build
zextras/carbonio-jetty-conf pull request #12
Opened 2024-01-17 15:40 UTC by frisonisland

Since appserver is made mostly of this repo files + some files present here: https://github.com/zextras/carbonio-build/tree/devel/rpmconf/Conf, the idea is to make this repo the "appserver", also by changing the repo name.

**What I did:**
- move required files from carbonio-build to this repo
- add Makefile to download extension jars to be included in appserver package
- define yap build + jenkinsfile

2024-01-18 13:06 UTC, keshavbhatt approved these changes

2024-01-18 13:24 UTC, M0Rf30 commented on .gitignore
> +/jars/
add artifacts folder

2024-01-18 13:24 UTC, M0Rf30 commented on Jenkinsfile
> +            label 'base-agent-v1'
base-agent-v2

2024-01-18 13:27 UTC, M0Rf30 requested changes

2024-01-18 13:27 UTC, M0Rf30 commented on Jenkinsfile
> +                                sh 'sudo yap build ubuntu /tmp/staging/package'
sh 'sudo yap build ubuntu /tmp/staging/package -s'
to avoid distro repo sync and make ci faster (cause there's no compilation of native stuff)

2024-01-18 13:27 UTC, M0Rf30 commented on Jenkinsfile
> +                                sh 'sudo yap build rocky /tmp/staging/package'
sh 'sudo yap build rocky /tmp/staging/package -s'
to avoid distro repo sync and make ci faster (cause there's no compilation of native stuff)

2024-01-19 08:22 UTC, frisonisland commented on .gitignore
> +/jars/
added

2024-01-19 08:28 UTC, M0Rf30 approved these changes

2024-01-30 09:32 UTC, merged